### ISSUE TITLE
HTTP Error 504 during execution

### ISSUE THREAD

**Issue by mikedolx** [axyyu/notion-clear-trash#11]
Hi,

today i tried your script but failed with the following exception message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 833, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3.9/site-packages/urllib3/connectionpool.py", line 819, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/usr/lib/python3.9/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/searchTrashPages (Caused by ResponseError('too many 504 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/git/notion-clear-trash/notion-clear-trash.py", line 25, in <module>
    block_ids = get_trash(client)
  File "/home/michael/git/notion-clear-trash/notion-clear-trash.py", line 10, in get_trash
    results = client.post('/api/v3/searchTrashPages', query)
  File "/home/michael/.local/lib/python3.9/site-packages/notion/client.py", line 253, in post
    response = self.session.post(url, json=data)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 507, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='www.notion.so', port=443): Max retries exceeded with url: /api/v3/searchTrashPages (Caused by ResponseError('too many 504 error responses'))

```

Any idea, what the problem could be?
Thanks and BR

**Comment by hyleore** [comment]
I got the same message. Something must have changed at Notion.
